version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  carservice:
    container_name: carservice
    image: carservice:latest
    depends_on:
      - "keyservice"
    build:
      context: CarService
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
  
  keyservice:
    container_name: keyservice
    image: keyservice:latest
    build:
      context: KeyService
      dockerfile: Dockerfile    
    networks:
      - services-network